### ISSUE TITLE
System Power Module Doesn't Work With This Theme

### ISSUE THREAD

**Issue by dsreyes1014** [JeffHoogland/MokshaDetour#2]
Quick heads up I love this theme but the power button reboot, suspend, or power off doesn't work.  When I click on the power button icon nothing pops up.

**Comment by dsreyes1014** [comment]
Also I'm on Enlightenment-0.20.5 by the way and EFL 1.17.0

**Comment by JeffHoogland** [comment]
This is a Moksha theme. It will not be fully compatible with newer versions of E. The API for that module changed between versions - that button works as expected with the theme under moksha.

**Comment by dsreyes1014** [comment]
Ok thanks Jeff.
